# Generated by Django 3.1.3 on 2024-04-26 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('escola', '0004_auto_20240426_1123'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aluno',
            name='celular',
        ),
    ]
